// This requires Shape as it is the parent class of all the children shapes to be created
const Shape = require('./Shape.js')

// This is a child of Shape, render a Triangle using svg literal template
class Triangle extends Shape {
    constructor(shapeColor, text, textColor) {
        // Super specifies the use of the Parent class constructors
        super(shapeColor, text, textColor);  
    };
    // This sets the specifications for the Triangle shape generated by the application.
    render() {
        return `<svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
              <polygon points="100, 15 200, 200 0, 200" fill="${this.shapeColor}"/>
              <text x="100" y="165" font-size="60" text-anchor="middle" fill="${this.textColor}">${this.text}</text>
            </svg>`
    };
};
//This exports the Triangle page to be accessed by other functions in other files
module.exports = Triangle;